### ISSUE TITLE
`Request per Second ` on page(/status) shows `NaN` sometimes

### ISSUE THREAD

**Issue by carlisliu** [capaj/koa-monitor#1]
`Request per Second` on page(/status) shows `NaN` sometimes
![koa-monitor-nan](https://cloud.githubusercontent.com/assets/2157653/18026172/4761ad7a-6c71-11e6-84e1-da06b5241650.png)

**Comment by capaj** [comment]
thanks for your report, I have seen this as well, will try to get that sorted out.
